# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d82b74248ad555ac6c213371121c13538941c9acfe3162ffc2e1d024dcb6b7978df53d2c71b49fe93d6e17c25c55c54a847e8fd0c8cf21125d785e264aff6caa

test:
  secret_key_base: 1296794fc6ca5b4adbca306b93520b386c663bab96a880a2c34a11d652ccab782bbacdc2ab39040ffb69fe76d700f714542f0bc0f08ecc32e9a475baba4961d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
